### ISSUE TITLE
tmr.create issue

### ISSUE THREAD

**Issue by derekb77** [heythisisnate/nodemcu-smartthings-sensors#9]
Nate,
Thanks for the write up, I was able to get everything loaded onto the nodeMCU with a caveat. I loaded your firmware fromt he link in the writeup and flashed with no issue. When I tried to connect and load to the nodeMCU I can never get a solid connection to upload files. I always get "Communication with MCU..." and it never connects. If I go with the default firmware I can load LUA files with no issue. But when I attempt to run I get an error at line 18 in the init.lua file with tmr.create(). I don't know if this is a firmware issue or something with the code. Please help, I feel so close!

**Comment by heythisisnate** [comment]
Have you tried toggling the RST button on and off again in ESplorer?

**Comment by derekb77** [comment]
I figured it out. Now I have a 501 error to solve.

**Comment by derekb77** [comment]
Nate I am actually getting a 500 error code in the nodeMCU. Everything seems to be working fine except that. I reran all the setup to get the auth codes. Still nothing.

**Comment by heythisisnate** [comment]
Can you check the _Live Logging_ tab in Smartthings for more details about the 500 error?

**Comment by derekb77** [comment]
7:54:05 AM:error java.lang.IllegalArgumentException: Command 'open' is not supported by device 43df5be4-96c2xxxxxxxxxxx of type 'Door / Window Sensor (SG)'. Supported commands: [configure] @ line 66

**Comment by derekb77** [comment]
I figured out my mistake. I didn't choose the nodeMCU connected sensors when I added them from the drop downcast of items. I choose a pre-configured item. I didn't know about the live logging, that helped for sure. Thanks for the tips. Will need to fix and retest. I will let you know when it works.
